### PR TITLE
Adding the remaining pages for section II

### PR DESCRIPTION
**Pull request by Achilihudaniel07**

### CODE REVIEW

**Review by mbragi — CHANGES_REQUESTED** [review]
Your app.js is behind the master branch, please pull n accept the changes on your machine before committing again

**Comment by mbragi** [comment]
Link pages with updated routes for next buttons in admin sections page

**Comment by Achilihudaniel07** [comment]
> Your app.js is behind the master branch, please pull n accept the changes on your machine before committing again

Okay Done

**Comment by Achilihudaniel07** [comment]
> Link pages with updated routes for next buttons in admin sections page

The link to proceed to the nextpage i guess?? like from section I to section II

**Comment by Achilihudaniel07** [comment]
> Link pages with updated routes for next buttons in admin sections page

>Done

**Pull request merged**
